#!/usr/bin/env python3
"""Extracts the official Noise test vectors for the two protocols kkproto implements
(Noise_XX_25519_ChaChaPoly_SHA256 and Noise_IK_25519_ChaChaPoly_SHA256) from three
independent public vector sets into the simple line format test_host/ reads.

Sources (downloaded as-is, their SHA-256 is recorded in the output header):
  cacophony  https://raw.githubusercontent.com/haskell-cryptography/cacophony/master/vectors/cacophony.txt
  snow       https://raw.githubusercontent.com/mcginty/snow/main/tests/vectors/snow.txt
  noise-c    https://raw.githubusercontent.com/rweather/noise-c/master/tests/vector/noise-c-basic.txt

usage: convert_vectors.py cacophony.txt snow.txt noisec.txt > noise_vectors.txt
"""
import hashlib, json, sys

WANT = ("Noise_XX_25519_ChaChaPoly_SHA256", "Noise_IK_25519_ChaChaPoly_SHA256")
FIELDS = ("init_prologue", "init_static", "init_ephemeral", "init_remote_static",
          "resp_prologue", "resp_static", "resp_ephemeral", "handshake_hash")

def main(paths):
    out = ["# Official Noise test vectors, filtered to the protocols kkproto implements.",
           "# Generated by tools/convert_vectors.py -- do not edit by hand."]
    count = 0
    for path, label in zip(paths, ("cacophony", "snow", "noise-c")):
        raw = open(path, "rb").read()
        out.append(f"# source {label}: sha256 {hashlib.sha256(raw).hexdigest()}")
        data = json.loads(raw)
        vectors = data["vectors"] if isinstance(data, dict) else data
        for i, v in enumerate(vectors):
            name = v.get("protocol_name") or v.get("name")
            if name not in WANT:
                continue
            out.append(f"vector {label}:{i} {name}")
            for f in FIELDS:
                if f in v:
                    out.append(f"{f} {v[f] or '-'}")
            for m in v["messages"]:
                out.append(f"msg {m['payload'] or '-'} {m['ciphertext']}")
            out.append("end")
            count += 1
    out.append(f"# {count} vectors")
    print("\n".join(out))

if __name__ == "__main__":
    main(sys.argv[1:4])
