#pragma once

// Client-side localization for the embedded Web UI.
// The API and DOM structure remain unchanged; this only translates
// user-visible labels, buttons, placeholders and common status text.

namespace web {

constexpr char RUSSIAN_LOCALIZATION_SCRIPT[] = R"JS(<script>
(function () {
  const RU = {
    "Unlock": "Разблокировать",
    "Accounts": "Учётные записи",
    "Help": "Помощь",
    "Settings": "Настройки",
    "+ New": "+ Новая",
    "Back": "Назад",
    "Recovery Codes": "Коды восстановления",
    "Import from file": "Импорт из файла",
    "Save": "Сохранить",
    "Cancel": "Отмена",
    "Set / Replace": "Задать / заменить",
    "Copy unused": "Копировать неиспользованные",
    "Reveal": "Показать",
    "Copy": "Копировать",
    "Clear": "Очистить",
    "Edit": "Изменить",
    "Delete": "Удалить",
    "Login": "Логин",
    "Password": "Пароль",
    "URL": "URL",
    "Notes": "Заметки",
    "TOTP Secret": "Секрет TOTP",
    "Category": "Категория",
    "Favorite": "Избранное",
    "Seed Phrase": "Сид-фраза",
    "English": "Английский",
    "Russian": "Русский",
    "General": "Общие",
    "Language": "Язык",
    "Display Brightness (0-100)": "Яркость дисплея (0–100)",
    "Screen Timeout (seconds, 0 = off)": "Тайм-аут экрана (секунды, 0 = выкл.)",
    "Save General": "Сохранить общие",
    "USB": "USB",
    "Quick Password (no PIN required)": "Быстрый пароль (PIN не требуется)",
    "Auto-switch keyboard layout for Cyrillic (best-effort, Alt+Shift)": "Автопереключение раскладки для кириллицы (по возможности, Alt+Shift)",
    "Save USB": "Сохранить USB",
    "Security": "Безопасность",
    "Auto Lock enabled": "Автоблокировка включена",
    "Auto Lock timeout": "Тайм-аут автоблокировки",
    "Off": "Выкл.",
    "1 min": "1 мин",
    "3 min": "3 мин",
    "5 min": "5 мин",
    "10 min": "10 мин",
    "15 min": "15 мин",
    "20 min": "20 мин",
    "25 min": "25 мин",
    "30 min": "30 мин",
    "35 min": "35 мин",
    "40 min": "40 мин",
    "45 min": "45 мин",
    "50 min": "50 мин",
    "55 min": "55 мин",
    "60 min": "60 мин",
    "Web UI permissions": "Разрешения Web UI",
    "View accounts": "Просмотр учётных записей",
    "Edit accounts": "Изменение учётных записей",
    "Export data": "Экспорт данных",
    "Change settings": "Изменение настроек",
    "Save Security": "Сохранить безопасность",
    "Wi-Fi": "Wi-Fi",
    "Mode": "Режим",
    "Disabled": "Отключён",
    "Station": "Станция",
    "Access Point": "Точка доступа",
    "STA SSID": "SSID станции",
    "STA Password": "Пароль станции",
    "AP SSID": "SSID точки доступа",
    "AP Password": "Пароль точки доступа",
    "Save Wi-Fi": "Сохранить Wi-Fi",
    "Password Generator": "Генератор паролей",
    "Password Gen": "Генератор паролей",
    "System": "Система",
    "About": "О программе",
    "Firmware": "Прошивка",
    "Device": "Устройство",
    "Flash Encryption": "Шифрование Flash",
    "On": "Вкл.",
    "Free heap": "Свободная память",
    "Internal storage": "Внутреннее хранилище",
    "microSD": "microSD",
    "unavailable": "недоступно",
    "present, usage unavailable": "установлена, использование недоступно",
    "not detected": "не обнаружена",
    "Help & keyboard": "Помощь и клавиатура",
    "Save failed": "Ошибка сохранения",
    "Wrong PIN": "Неверный PIN",
    "Locked out, try again later": "Ввод заблокирован, попробуйте позже",
    "Not authenticated": "Не выполнена аутентификация",
    "No PIN configured yet -- set one up on the device first": "PIN ещё не настроен — сначала задайте его на устройстве",
    "Too many failed attempts -- WiFi disabled": "Слишком много неудачных попыток — Wi-Fi отключён",
    "Missing 'pin' field": "Отсутствует поле PIN",
    "Invalid JSON": "Недопустимый JSON",
    "Failed to save": "Не удалось сохранить"
  };

  const ATTRS = ["placeholder", "title", "aria-label"];

  function translateTextNode(node) {
    const text = node.nodeValue;
    if (!text || !text.trim()) return;
    const trimmed = text.trim();
    if (RU[trimmed]) {
      node.nodeValue = text.replace(trimmed, RU[trimmed]);
      return;
    }

    // Common dynamic strings generated by the Web UI JavaScript.
    let out = text;
    out = out.replace(/^Firmware:\s*/, RU["Firmware"] + ": ");
    out = out.replace(/^Device:\s*/, RU["Device"] + ": ");
    out = out.replace(/^Flash Encryption:\s*/, RU["Flash Encryption"] + ": ");
    out = out.replace(/^Free heap:\s*/, RU["Free heap"] + ": ");
    out = out.replace(/^Internal storage:\s*/, RU["Internal storage"] + ": ");
    if (out !== text) node.nodeValue = out;
  }

  function translate(root) {
    if (!root) return;
    const walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT);
    const nodes = [];
    while (walker.nextNode()) nodes.push(walker.currentNode);
    nodes.forEach(translateTextNode);

    if (root.nodeType === Node.ELEMENT_NODE) {
      ATTRS.forEach(function (attr) {
        if (root.hasAttribute && root.hasAttribute(attr)) {
          const value = root.getAttribute(attr);
          if (RU[value]) root.setAttribute(attr, RU[value]);
        }
      });
      if (root.querySelectorAll) {
        root.querySelectorAll("[placeholder],[title],[aria-label]").forEach(function (el) {
          ATTRS.forEach(function (attr) {
            if (el.hasAttribute(attr)) {
              const value = el.getAttribute(attr);
              if (RU[value]) el.setAttribute(attr, RU[value]);
            }
          });
        });
      }
    }
  }

  async function applyRussianIfSelected() {
    try {
      const response = await fetch("api/v1/settings", { cache: "no-store" });
      if (!response.ok) return;
      const data = await response.json();
      if (data && data.data && data.data.general && data.data.general.language === "russian") {
        document.documentElement.lang = "ru";
        translate(document.body);

        // Observe only newly inserted DOM nodes. Do NOT observe characterData:
        // translateTextNode() changes text nodes itself, which would otherwise
        // trigger this observer again indefinitely and can hang the browser.
        const observer = new MutationObserver(function (mutations) {
          mutations.forEach(function (m) {
            m.addedNodes.forEach(function (node) {
              if (node.nodeType === Node.ELEMENT_NODE || node.nodeType === Node.TEXT_NODE) {
                translate(node);
              }
            });
          });
        });
        observer.observe(document.body, { childList: true, subtree: true });
      }
    } catch (_) {
      // Keep the original English Web UI if settings cannot be read.
    }
  }

  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", applyRussianIfSelected);
  } else {
    applyRussianIfSelected();
  }
})();
</script>)JS";

} // namespace web
