#pragma once

#include "settings/settings_types.hpp"

namespace ui::i18n {

enum class Key : uint8_t {
    MainMenu,
    Accounts,
    Settings,
    Backup,
    Lock,
    About,
    FontTest,
    General,
    Language,
    Theme,
    Brightness,
    ScreenTimeout,
    Save,
    RotateSelect,
    OkOpen,
    BackReturn,
    RotateChange,
    OkBackConfirm,
    OkOpenBackCancel,
    English,
    Russian,
    Off,
    SaveFailed,
    Dark,
    Light,
    Orientation,
    Rotate0,
    Rotate180,
    Auto,
    // AccountsScreen / VaultListScreen / AccountViewScreen -- see
    // localization.cpp's own EN/RU arrays for the exact wording.
    All,
    Favorites,
    Categories,
    Search,
    OkOpenBackReturn,
    VaultTitle,
    VaultEmpty,
    RotateSelectOkOpenHoldOkNewBackReturn,
    AccountTitle,
    AddToFavorites,
    RemoveFromFavorites,
    FieldCategory,
    FieldNotes,
    FieldUrl,
    FieldUsername,
    Delete,
    Edit,
    DeleteFailed,
    UpdateFailed,
    NoUnusedCodesLeft,
    NotAllowed,
    OtpValueFmt,
    OtpInvalidSecret,
    OtpNoTimeSync,
    PasswordValueFmt,
    PasswordMasked,
    PressOkAgainToDelete,
    PrintOtp,
    PrintPassword,
    PrintRecoveryCodes,
    PrintSeedPhrase,
    PrintUrl,
    PrintUsername,
    RotateScrollBackReturn,
    RotateScrollOkRevealHideBackReturn,
    RotateSelectOkRunBackReturn,
    RecoveryCodesTitle,
    SeedPhraseTitle,
    RevealPassword,
    ViewRecoveryCodes,
    ViewSeedPhrase,
    EntryNotFound,
    FavoriteLabel,
    ConfirmActionFmt,
};

void set_language(settings::Language language);
settings::Language language();
const char* tr(Key key);

} // namespace ui::i18n
