#pragma once

#include "settings/settings_types.hpp"

namespace ui::i18n {

enum class Key : uint8_t {
    MainMenu,
    Accounts,
    Settings,
    Backup,
    Lock,
    About,
    FontTest,
    General,
    Language,
    Theme,
    Brightness,
    ScreenTimeout,
    Save,
    RotateSelect,
    OkOpen,
    BackReturn,
    RotateChange,
    OkBackConfirm,
    OkOpenBackCancel,
    English,
    Russian,
    Off,
    SaveFailed,
    Dark,
    Light,
    Orientation,
    Rotate0,
    Rotate180,
    Auto,
    // AccountsScreen / VaultListScreen / AccountViewScreen -- see
    // localization.cpp's own EN/RU arrays for the exact wording.
    All,
    Favorites,
    Categories,
    Search,
    OkOpenBackReturn,
    VaultTitle,
    VaultEmpty,
    RotateSelectOkOpenHoldOkNewBackReturn,
    AccountTitle,
    AddToFavorites,
    RemoveFromFavorites,
    FieldCategory,
    FieldNotes,
    FieldUrl,
    FieldUsername,
    Delete,
    Edit,
    DeleteFailed,
    UpdateFailed,
    NoUnusedCodesLeft,
    NotAllowed,
    OtpValueFmt,
    OtpInvalidSecret,
    OtpNoTimeSync,
    PasswordValueFmt,
    PasswordMasked,
    PressOkAgainToDelete,
    PrintOtp,
    PrintPassword,
    PrintRecoveryCodes,
    PrintSeedPhrase,
    PrintUrl,
    PrintUsername,
    RotateScrollBackReturn,
    RotateScrollOkRevealHideBackReturn,
    RotateSelectOkRunBackReturn,
    RecoveryCodesTitle,
    SeedPhraseTitle,
    RevealPassword,
    ViewRecoveryCodes,
    ViewSeedPhrase,
    EntryNotFound,
    FavoriteLabel,
    ConfirmActionFmt,
    FieldTooLong,
    EditEntryTitle,
    NewEntryTitle,
    EditingFmt,
    EntrySaved,
    FieldFavorite,
    NameUsernameCannotBeEmpty,
    FieldNameUsername,
    Yes,
    No,
    EditFooterTyping,
    EditFooterViewUnsaved,
    EditFooterOtpSecret,
    FieldOtpSecret,
    OtpSecretInvalidBase32,
    PasswordGenerated,
    PasswordGenerationFailed,
    FieldPassword,
    BackupTitle,
    CreateBackup,
    RestoreBackupTitle,
    ExportVault,
    ImportVault,
    RefreshSdCard,
    FormatSdCard,
    BackupFooterSelectConfirm,
    BackupFooterImport,
    BackupFooterRun,
    BackupCreatedFmt,
    BackupCreateFailedLockedNoSd,
    ExportedFmt,
    ExportFailedLockedNoSd,
    SdCardMountedSizeFmt,
    SdCardMounted,
    SdCardUnreadable,
    NoSdCardDetected,
    ConfirmEraseCard,
    SdCardFormatted,
    FormatFailed,
    NoBackupsFound,
    ConfirmOverwriteVault,
    RestoreFailed,
    RestoredRestarting,
    NoImportFiles,
    ImportedSkippedFmt,
    ConfirmBackupActionFmt,
    ConfirmBackupFileActionFmt,
};

void set_language(settings::Language language);
settings::Language language();
const char* tr(Key key);

} // namespace ui::i18n
